version: '3'

services:
  database:
   image: mysql
   environment:
    - MYSQL_ROOT_PASSWORD=root
   ports:
    - 3307:3306 
   networks:
    - mynetwork
    
    
  user-service:
   image: user-service-docker
   ports:
    - "8081:8081"
   networks:
    - mynetwork
   depends_on:
    - database
   # - eureka-service
   environment:
    - spring.datasource.url=jdbc:mysql://database:3306/EcommerceMicroservices?createDatabaseIfNotExist=true
    - spring.datasource.username=root
    - spring.datasource.password=root
    
#    - JAVA_OPTS=
#      -      
    
    
    
#  user-service:
#   build: ./build
#   ports:
#    - 8081:8081 
#   networks:
#    - mynetwork
#   depends_on:
#    - database
#   environment:				
#     - spring.datasource.url=jdbc:mysql://database:3306/EcommerceMicroservices?createDatabaseIfNotExist=true
#     - spring.datasource.username=root
#     - spring.datasource.password=root
     
    
    
    
    
networks:
  mynetwork: